export const VISUAL_REVISION = 2;

export const VISUAL_TARGETS = [
  'Cinematic color management foundation',
  'Deterministic astronomical star distribution',
  'High-quality stellar sprite shader',
  'Galactic / deep-sky structure',
  'Starfield stability / antialiasing',
  'Starfield / exposure integration',
  'Eliminate geometric Siege-Wall object',
  'Organic Siege-Wall propagation',
  'Realistic stellar photosphere',
  'Corona / prominences',
  'Star-driven system illumination',
  'Collapse thermodynamics',
  'Shock / mass ejection',
  'True event-horizon shadow',
  'Accretion / infall structure',
  'Relativistic brightness asymmetry',
  'Photon-ring detail',
  'Gravitational lensing',
  'Black-hole compositing coherence',
  'Post-collapse lighting',
  'Real planetary topology',
  'Planetary PBR surface',
  'Atmospheric scattering',
  'Realistic cloud system',
  'Geographic city lights',
  'Day/night terminator',
  'Planetary orbital inertia',
  'Tidal / atmospheric stripping',
  'Civilization failure',
  'Orbital infrastructure quality',
  'Exterior spacecraft quality',
  'Spacecraft propulsion / mass',
  'Station exterior hero pass',
  'Camera mass / cinematography',
  'Station interior PBR material system',
  'Observation glass',
  'Interior architectural detail',
  'Practical lighting',
  'True structural breach',
  'Decompression VFX',
  'Debris material / mass / collision',
  'Replace primitive NPC silhouettes',
  'NPC material / contact / silhouette',
  'NPC locomotion',
  'NPC zero-g / inertial response',
  'Shard God dossier fidelity',
  'Tactical console redesign',
  'HUD / forensic replay polish',
  'Cinematic post-processing',
  'Final station-loss cinematic / integrated wow pass'
];
